version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: english-project:latest
    container_name: english-project
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
